#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<string.h>
//#include"parser.h"
#include"lexer.h"
#include"symbolTable.h"
//#include"semanticAnalyzer.h"

// Batch       - 55
// Avinav Singla 2010A7PS125P
// Kanav         2010A7PS152P


int main(int argc,char *argv[])
{
	parseTree ptree;
	abstractSyntaxTree A;
	SPointer sp;
	FPointer fpointer;
	int T[50][54],i=0,j=0,totalallocatedmemory = 0;
	int *totalAllocatedMemory;	
	char newline[] = "\n";
	char testcopy[] = "testcopy.txt";
	int option = 0;
	FILE *G;
	FILE *fp;
	FILE *fp1;
	FILE *fp2;
	FILE *fx;
	TokenList tokens;
	tokens=initialize();
	link header=tokens.head;

	totalAllocatedMemory = &(totalallocatedmemory);	

        printf("1. See the token stream generated by lexical analyzer.\n");
	printf("2. Print the parse tree (parsetreeOutFile.txt)\n");
	printf("3. Print the abstract tree (ASTOutFile.txt)\n");
	printf("4. Print the Symbol Table on Standard Output(Screen)\n");
	printf("5. See semantic errors on Standard Output(Screen)\n");
	scanf("%d",&option);
	G = fopen("grammar.txt","r");
	
	fp = fopen(argv[2],"w");
 	
	fp1 = fopen(argv[3],"w");
	fx=fopen(argv[4],"w");
	sp = createSymbolTable(10,10,10);
	fpointer = fillingGlobalBucket(sp); 

	for(i=0;i<50;i++)
	for(j=0;j<54;j++)
		T[i][j] = 0;
	switch(option){
	case 1:
		fp2 = fileEdit(argv[1]);
		fp2 = fopen("testcopy.txt","r");
		tokenInfo t;
		strcpy(t.tokenName,argv[1]);	
		while(strcmp(t.tokenName,"END"))
		{		
		t = getNextToken(fp2,&header);
		printf("%s %s %d\n",t.tokenName,t.lexemeName,t.lineno);
		}
		break;
	case 2:
		fp2 = fileEdit(argv[1]);
		createParseTable(G,T);
		ptree = parseInputSourceCode(testcopy,T);
		ptree->temphead = ptree->head;
		printParseTree(ptree,fp);
		break;
	case 3:
		fp2 = fileEdit(argv[1]);
		createParseTable(G,T);
		ptree = parseInputSourceCode(testcopy,T);
		ptree->temphead = ptree->head;
		createAbstractSyntaxtree(ptree,A);
		printAST(ptree,fp1,totalAllocatedMemory);
		printf("Total Allocated Memory is %d bytes\n",*(totalAllocatedMemory)*sizeof(pnode));
		break;
	case 4:
		fp2 = fileEdit(argv[1]);
		createParseTable(G,T);
		ptree = parseInputSourceCode(testcopy,T);
		ptree->temphead = ptree->head;
		createAbstractSyntaxtree(ptree,A);
		printAST(ptree,fp1,totalAllocatedMemory);
		ptree->temphead = ptree->head;
		//printf("%s",ptree->temphead->info.NodeSymbol);
		findingFunctions(sp,fpointer,ptree);
		printSymbolTable(sp);
		
		ptree->temphead = ptree->head;
		MASM(ptree,sp,fx);
		/*fprintf(fx,".MODEL TINY\n.DATA\n");
		varDec(sp,fx);
		fseek(fx,0,SEEK_END);
		fprintf(fx,".CODE\nSTART\n");
		code(ptree,fx);
		fprintf(fx,"END START\n");
		fclose(fx);*/
	break;
	/*case 5:
		fp2 = fileEdit(argv[1]);
		createParseTable(G,T);
		ptree = parseInputSourceCode(testcopy,T);
		ptree->temphead = ptree->head;
		createAbstractSyntaxtree(ptree,A);
		printAST(ptree,fp1,totalAllocatedMemory);
		ptree->temphead = ptree->head;
		//printf("%s",ptree->temphead->info.NodeSymbol);
		findingFunctions(sp,fpointer,ptree);
		//printSymbolTable(sp);
		ptree->temphead = ptree->head;
		//printf("here\n");
		semanticanalyzer(ptree,fpointer,sp);
		//printSymbolTable(sp);
		break;*/
	}
	
	
	fclose(fp);
		
	fclose(G);
	
	fclose(fp1);
	
	return 0;
}

